title: Deep Learning para Bioinformática
description: Página do curso "Deep Learning para Bioinformática"
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: "false"
